import { useClaudeAgent, type UseClaudeAgentReturn } from "./useClaudeAgent.js";
import { useACPAgent, type UseACPAgentReturn } from "./useACPAgent.js";
import type { AgentType, UseAgentReturn } from "../types.js";

const NOOP_ASYNC = async () => {};
const NOOP = () => {};

export function useAgent(agentType: AgentType | null): UseAgentReturn {
  const claude = useClaudeAgent();
  const acp = useACPAgent();

  if (agentType === "claude") {
    return mapClaude(claude);
  }
  if (agentType === "acp") {
    return mapACP(acp);
  }

  // No agent selected yet
  return {
    agentType: null,
    connectionPhase: "idle",
    connectionStatus: null,
    error: null,
    messages: [],
    currentTurnBlocks: [],
    isAgentTurn: false,
    isStreaming: false,
    isSendingPrompt: false,
    usage: null,
    initInfo: null,
    permissionMode: null,
    currentModel: null,
    pendingControlRequest: null,
    plan: null,
    toolActivity: [],
    fileOps: [],
    terminals: new Map(),
    currentMode: null,
    availableModes: [],
    configOptions: [],
    availableModels: [],
    currentModelId: null,
    pendingPermission: null,
    pendingElicitation: null,
    agentInfo: null,
    connectionDetails: { protocolVersion: null, agentCapabilities: null, clientCapabilities: null, sessionMeta: null },
    authMethods: [],
    isAuthenticated: false,
    authDismissed: false,
    availableCommands: [],
    sessions: [],
    isLoadingSessions: false,
    autoApprovePermissions: true,
    devboxId: null,
    axonId: null,
    sessionId: null,
    runloopUrl: null,
    axonEvents: [],
    start: NOOP_ASYNC,
    sendMessage: NOOP_ASYNC,
    cancel: NOOP_ASYNC,
    shutdown: NOOP_ASYNC,
    setAutoApprovePermissions: NOOP_ASYNC,
    setModel: NOOP_ASYNC,
    setPermissionMode: NOOP_ASYNC,
    sendControlResponse: NOOP_ASYNC,
    setMode: NOOP_ASYNC,
    setACPModel: NOOP_ASYNC,
    setConfigOption: NOOP_ASYNC,
    authenticate: NOOP_ASYNC,
    dismissAuth: NOOP,
    respondToPermission: NOOP_ASYNC,
    cancelPermission: NOOP_ASYNC,
    respondToElicitation: NOOP_ASYNC,
    createNewSession: NOOP_ASYNC,
    switchSession: NOOP_ASYNC,
    refreshSessions: NOOP_ASYNC,
  };
}

function mapClaude(c: UseClaudeAgentReturn): UseAgentReturn {
  return {
    agentType: "claude",
    connectionPhase: c.connectionPhase,
    connectionStatus: c.connectionStatus,
    error: c.error,
    messages: c.messages,
    currentTurnBlocks: c.currentTurnBlocks,
    isAgentTurn: c.isAgentTurn,
    isStreaming: c.isStreaming,
    isSendingPrompt: c.isSendingPrompt,
    usage: c.usage,
    initInfo: c.initInfo,
    permissionMode: c.permissionMode,
    currentModel: c.currentModel,
    pendingControlRequest: c.pendingControlRequest,
    plan: null,
    toolActivity: [],
    fileOps: [],
    terminals: new Map(),
    currentMode: null,
    availableModes: [],
    configOptions: [],
    availableModels: [],
    currentModelId: null,
    pendingPermission: null,
    pendingElicitation: null,
    agentInfo: null,
    connectionDetails: { protocolVersion: null, agentCapabilities: null, clientCapabilities: null, sessionMeta: null },
    authMethods: [],
    isAuthenticated: false,
    authDismissed: false,
    availableCommands: [],
    sessions: [],
    isLoadingSessions: false,
    autoApprovePermissions: c.autoApprovePermissions,
    devboxId: c.devboxId,
    axonId: c.axonId,
    sessionId: null,
    runloopUrl: c.runloopUrl,
    axonEvents: c.axonEvents,
    start: (config) => c.start(config as any),
    sendMessage: c.sendMessage,
    cancel: c.cancel,
    shutdown: c.shutdown,
    setAutoApprovePermissions: c.setAutoApprovePermissions,
    setModel: c.setModel,
    setPermissionMode: c.setPermissionMode,
    sendControlResponse: c.sendControlResponse,
    setMode: NOOP_ASYNC,
    setACPModel: NOOP_ASYNC,
    setConfigOption: NOOP_ASYNC,
    authenticate: NOOP_ASYNC,
    dismissAuth: NOOP,
    respondToPermission: NOOP_ASYNC,
    cancelPermission: NOOP_ASYNC,
    respondToElicitation: NOOP_ASYNC,
    createNewSession: NOOP_ASYNC,
    switchSession: NOOP_ASYNC,
    refreshSessions: NOOP_ASYNC,
  };
}

function mapACP(a: UseACPAgentReturn): UseAgentReturn {
  return {
    agentType: "acp",
    connectionPhase: a.connectionPhase,
    connectionStatus: a.connectionStatus,
    error: a.error,
    messages: a.messages,
    currentTurnBlocks: a.currentTurnBlocks,
    isAgentTurn: a.isAgentTurn,
    isStreaming: a.isStreaming,
    isSendingPrompt: a.isSendingPrompt,
    usage: a.usage,
    initInfo: null,
    permissionMode: null,
    currentModel: null,
    pendingControlRequest: null,
    plan: a.plan,
    toolActivity: a.toolActivity,
    fileOps: a.fileOps,
    terminals: a.terminals,
    currentMode: a.currentMode,
    availableModes: a.availableModes,
    configOptions: a.configOptions,
    availableModels: a.availableModels,
    currentModelId: a.currentModelId,
    pendingPermission: a.pendingPermission,
    pendingElicitation: a.pendingElicitation,
    agentInfo: a.agentInfo,
    connectionDetails: a.connectionDetails,
    authMethods: a.authMethods,
    isAuthenticated: a.isAuthenticated,
    authDismissed: a.authDismissed,
    availableCommands: a.availableCommands,
    sessions: a.sessions,
    isLoadingSessions: a.isLoadingSessions,
    autoApprovePermissions: a.autoApprovePermissions,
    devboxId: a.devboxId,
    axonId: a.axonId,
    sessionId: a.sessionId,
    runloopUrl: a.runloopUrl,
    axonEvents: a.axonEvents,
    start: (config) => a.start(config as any),
    sendMessage: a.sendMessage,
    cancel: a.cancel,
    shutdown: a.shutdown,
    setAutoApprovePermissions: a.setAutoApprovePermissions,
    setModel: NOOP_ASYNC,
    setPermissionMode: NOOP_ASYNC,
    sendControlResponse: NOOP_ASYNC,
    setMode: a.setMode,
    setACPModel: a.setModel,
    setConfigOption: a.setConfigOption,
    authenticate: a.authenticate,
    dismissAuth: a.dismissAuth,
    respondToPermission: a.respondToPermission,
    cancelPermission: a.cancelPermission,
    respondToElicitation: a.respondToElicitation as (requestId: string, action: unknown) => Promise<void>,
    createNewSession: a.createNewSession,
    switchSession: a.switchSession,
    refreshSessions: a.refreshSessions,
  };
}
